# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RhamaPlugin
                                 A QGIS plugin
 calcula o volume da superfície raster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-02-11
        copyright            : (C) 2022 by Guilherme B. Souza
        email                : guilherme.souza@rhama.com.br
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RhamaPlugin class from file RhamaPlugin.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .volume_surface1 import RhamaPlugin
    return RhamaPlugin(iface)
