# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RhamaPlugin
                                 A QGIS plugin
 calcula o volume da superfície raster
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2022-02-11
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Guilherme B. Souza
        email                : guilherme.souza@rhama.com.br
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QFileDialog
from qgis.core import *

# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .volume_surface1_dialog import RhamaPluginDialog
import os.path
import processing

import os
from osgeo import ogr


class RhamaPlugin:
    """QGIS Plugin Implementation."""

    def __init__(self, iface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class
            which provides the hook by which you can manipulate the QGIS
            application at run time.
        :type iface: QgsInterface
        """
        # Save reference to the QGIS interface
        self.iface = iface
        # initialize plugin directory
        self.plugin_dir = os.path.dirname(__file__)
        # initialize locale
        locale = QSettings().value('locale/userLocale')[0:2]
        locale_path = os.path.join(
            self.plugin_dir,
            'i18n',
            'RhamaPlugin_{}.qm'.format(locale))

        if os.path.exists(locale_path):
            self.translator = QTranslator()
            self.translator.load(locale_path)
            QCoreApplication.installTranslator(self.translator)

        # Declare instance attributes
        self.actions = []
        self.menu = self.tr(u'&Volume Surface1')

        # Check if plugin was started the first time in current QGIS session
        # Must be set in initGui() to survive plugin reloads
        self.first_start = None

    # noinspection PyMethodMayBeStatic
    def tr(self, message):
        """Get the translation for a string using Qt translation API.

        We implement this ourselves since we do not inherit QObject.

        :param message: String for translation.
        :type message: str, QString

        :returns: Translated version of message.
        :rtype: QString
        """
        # noinspection PyTypeChecker,PyArgumentList,PyCallByClass
        return QCoreApplication.translate('RhamaPlugin', message)


    def add_action(
        self,
        icon_path,
        text,
        callback,
        enabled_flag=True,
        add_to_menu=True,
        add_to_toolbar=True,
        status_tip=None,
        whats_this=None,
        parent=None):
        """Add a toolbar icon to the toolbar.

        :param icon_path: Path to the icon for this action. Can be a resource
            path (e.g. ':/plugins/foo/bar.png') or a normal file system path.
        :type icon_path: str

        :param text: Text that should be shown in menu items for this action.
        :type text: str

        :param callback: Function to be called when the action is triggered.
        :type callback: function

        :param enabled_flag: A flag indicating if the action should be enabled
            by default. Defaults to True.
        :type enabled_flag: bool

        :param add_to_menu: Flag indicating whether the action should also
            be added to the menu. Defaults to True.
        :type add_to_menu: bool

        :param add_to_toolbar: Flag indicating whether the action should also
            be added to the toolbar. Defaults to True.
        :type add_to_toolbar: bool

        :param status_tip: Optional text to show in a popup when mouse pointer
            hovers over the action.
        :type status_tip: str

        :param parent: Parent widget for the new action. Defaults None.
        :type parent: QWidget

        :param whats_this: Optional text to show in the status bar when the
            mouse pointer hovers over the action.

        :returns: The action that was created. Note that the action is also
            added to self.actions list.
        :rtype: QAction
        """

        icon = QIcon(icon_path)
        action = QAction(icon, text, parent)
        action.triggered.connect(callback)
        action.setEnabled(enabled_flag)

        if status_tip is not None:
            action.setStatusTip(status_tip)

        if whats_this is not None:
            action.setWhatsThis(whats_this)

        if add_to_toolbar:
            # Adds plugin icon to Plugins toolbar
            self.iface.addToolBarIcon(action)

        if add_to_menu:
            self.iface.addPluginToMenu(
                self.menu,
                action)

        self.actions.append(action)

        return action

    def initGui(self):
        """Create the menu entries and toolbar icons inside the QGIS GUI."""

        icon_path = ':/plugins/volume_surface1/icon.png'
        self.add_action(
            icon_path,
            text=self.tr(u'Volume Surface1'),
            callback=self.run,
            parent=self.iface.mainWindow())

        # will be set False in run()
        self.first_start = True


    def unload(self):
        """Removes the plugin menu item and icon from QGIS GUI."""
        for action in self.actions:
            self.iface.removePluginMenu(
                self.tr(u'&Volume Surface1'),
                action)
            self.iface.removeToolBarIcon(action)
            
    def carregaVetor(self):
        
        self.dlg.comboBox.clear()
        lista_layers = [layer for layer in QgsProject.instance().mapLayers().values()]
        lista_layers_vetor = ["oi","tchau"]
        for layer in lista_layers :
            
            if layer.type() == QgsMapLayer.VectorLayer:
                lista_layers_vetor.append(layer.name())
        self.dlg.comboBox.addItems(lista_layers_vetor)
        
        
    def abrirVetor(self):
        """abre a janela do dialog para abrir um layer para aplicar o buffer"""
        self.dlg.comboBox.clear()
        
        camada_abrir = str(QFileDialog.getOpenFileName(caption = "Escolha a camada", filter = "TaggedImageFile (*.*)")[0])

        if(camada_abrir != ""):

            self.iface.addVectorLayer(camada_abrir, str.split(os.path.basename(camada_abrir),".")[0],"ogr")

            self.carregaVetor()
            

    def calculo(self):
        # Set the path to your folder and the DTM file
        projectPath = "Z:/advanced/stagevolume"
        inputRasterDEM = "GPKG:Z:/advanced/stagevolume/data_stagevolume.gpkg:DTM"
        demLayer = self.iface.addRasterLayer(inputRasterDEM,"DEM","gdal")
        

    def camadaEnt(self):
        """definir uma leyaer especifica no comboBox """
        layer = None
        nomecamada = self.dlg.comboBox.currentText()
        demLayer = self.iface.addRasterLayer(nomecamada,"DEM","gdal")

        return demLayer
        
    def numeroBanda(self):
        camadaBanda = self.dlg.spinBox.value()
        return camadaBanda
        
        
    def nivelBase(self):
        camadaNBase = self.dlg.doubleSpinBox.value()
        return camadaNBase
        
    def definirSaida(self):
        """abre a janela do dialog para definir um nome e um local para a layer ser gerada"""
        
        self.camada_salvar = str(QFileDialog.getOpenFileName(caption = "Escolha a camada", filter = "TaggedImageFile (*.tif)")[0])
       
        
        
    def variaveis(self):
        """ deifine as variaveis utilizada na função run """
        self.camada = self.camadaEnt()
        self.saida = self.dlg.lineEdit.text()
        self.largura = self.nivelBase()
        self.banda = self.numeroBanda()

    def run(self):
        """Run method that performs all the real work"""

        # Create the dialog with elements (after translation) and keep reference
        # Only create GUI ONCE in callback, so that it will only load when the plugin is started
        if self.first_start == True:
            self.first_start = False
            self.dlg = RhamaPluginDialog()

        # show the dialog
        self.dlg.show()
        #adicionando as funções criadas
        self.carregaVetor()
        self.dlg.toolButton.clicked.connect(self.abrirVetor)
        self.dlg.toolButton_2.clicked.connect(self.definirSaida)
        # Run the dialog event loop
        result = self.dlg.exec_()
        # See if OK was pressed
        if result:
            # chamando as variaveis
            self.variaveis()
            
            #aplicando o buffer - usando a ferramenta do processamento do qgis
            buffer = processing.run("native:buffer",{'INPUT':self.camada,
            'BAND': self.banda,
            'LEVEL': self.largura,
            'METHOD': 1,
            'OUTPUT_HTML_FILE':'TEMPORARY_OUTPUT',
            'OUTPUT_TABLE': self.saida})
            
            # carregando o resultado na tela
            self.iface.addVectorLayer(self.saida, str.split(os.path.basename(self.saida),".")[0],"ogr")
            
            pass
